version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  myadimin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1

  dump:  
   build: ./docker/Dumper/  
   volumes:  
    - ./docker/Dumper/:/var/db/  
   command: sh -c "sleep 20 && /usr/bin/mysql -h mysql -uroot -ppassword < /var/db/dump.sql"  
   depends_on:  
    - mysql 